# GitHub Labels Configuration
# This file configures the labels for the GitHub repository

labels:
  # Type Labels
  - name: "type:bug"
    color: "d73a4a"
    description: "Bug report"
  - name: "type:feature"
    color: "a2eeef"
    description: "Feature request"
  - name: "type:enhancement"
    color: "84b6eb"
    description: "Enhancement or improvement"
  - name: "type:docs"
    color: "0075ca"
    description: "Documentation"
  - name: "type:discussion"
    color: "d4c5f9"
    description: "Discussion topic"
  - name: "type:refactor"
    color: "fbca04"
    description: "Code refactoring"

  # Priority Labels
  - name: "priority:critical"
    color: "b60205"
    description: "Critical priority, needs immediate attention"
  - name: "priority:high"
    color: "e99695"
    description: "High priority"
  - name: "priority:medium"
    color: "fff8c5"
    description: "Medium priority"
  - name: "priority:low"
    color: "c2e0c6"
    description: "Low priority"

  # Status Labels
  - name: "status:in-review"
    color: "5319e7"
    description: "Currently under review"
  - name: "status:needs-review"
    color: "006b75"
    description: "Needs review"
  - name: "status:ready"
    color: "2da44e"
    description: "Ready to be picked up"
  - name: "status:in-progress"
    color: "f6f8fa"
    description: "Currently being worked on"
  - name: "status:blocked"
    color: "e11d21"
    description: "Blocked, cannot proceed"

  # Area Labels
  - name: "area:core"
    color: "1f883d"
    description: "Related to core engine"
  - name: "area:cli"
    color: "0366d6"
    description: "Related to CLI"
  - name: "area:server"
    color: "0366d6"
    description: "Related to web server"
  - name: "area:bridge"
    color: "0366d6"
    description: "Related to FFI bridge"
  - name: "area:web"
    color: "0366d6"
    description: "Related to web UI"
  - name: "area:docs"
    color: "0366d6"
    description: "Related to documentation"
  - name: "area:infra"
    color: "0366d6"
    description: "Related to infrastructure"

  # Complexity Labels
  - name: "complexity:small"
    color: "c5def5"
    description: "Small task (1-2 hours)"
  - name: "complexity:medium"
    color: "c2e0c6"
    description: "Medium task (3-5 hours)"
  - name: "complexity:large"
    color: "84b6eb"
    description: "Large task (1-2 days)"

  # Good First Issue
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
